name: "Build and Test - MacOS Latest"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-latest-build:
    uses: ./.github/workflows/build-test.yml
    with:
      os: macos-latest